server:
  address: 0.0.0.0
  port: 8000

spring:
    application:
        name: api-gateway
    cloud:
       gateway:
          routes:
            - id: user-service
              uri: lb://USER-SERVICE
              predicates:
                - Path=/api/v1/users/**

            - id: fraud-service
              uri: lb://FRAUD-SERVICE
              predicates:
                - Path=/api/v1/fraud-check/**
          default-filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
          globalcors:
            corsConfigurations:
              '[/**]':
                allowedOrigins: "*"
                allowedHeaders: "*"
                allowedMethods:
                  - GET
                  - POST
                  - DELETE
                  - PUT
                  - OPTIONS

eureka:
  client:
    service-url:
      defaultZone: http://@eureka-server-service.hostname@:8761/eureka
    fetch-registry: true
    register-with-eureka: true

logging:
  level:
    root: info
