server:
    port: 8000

spring:
    application:
        name: api-gateway
    cloud:
       gateway:
          routes:
            - id: user
              uri: lb://USER-SERVICE
              predicates:
                - Path=/api/v1/users/**
          default-filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
          globalcors:
            corsConfigurations:
              '[/**]':
                allowedOrigins: "*"
                allowedHeaders: "*"
                allowedMethods:
                  - GET
                  - POST
                  - DELETE
                  - PUT
                  - OPTIONS

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

management:
  endpoints:
    web:
      exposure:
        include: 'prometheus,info,health'
  tracing:
    sampling:
      probability: 1.0
