server:
  address: 0.0.0.0
  port: 8080
  error:
    include-message: always

frontend-react:
  user-service-url: http://localhost:8000/

spring:
  application:
    name: user-service
  datasource:
    username: username
    password: password
    url: jdbc:postgresql://@postgres.hostname@:5432/_user
  ## Hibernate properties
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  ## Flyway properties
  flyway:
    enabled: true
    # uncomment these 3 lines at initial setup (should be used when you want to save initial db data)
    baseline-on-migrate: true
    baseline-description: init
    baseline-version: 0

eureka:
  client:
    service-url:
      defaultZone: http://@eureka-server-service.hostname@:8761/eureka
    fetch-registry: true
    register-with-eureka: true

logging:
  level:
    root: info
    org:
      flywaydb:
        core: DEBUG
      springframework:
        security: info

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
