server:
  address: @app-server-address@
  port: 8081

spring:
  application:
    name: fraud-service
  datasource:
    username: username
    password: password
    url: jdbc:postgresql://@postgres.hostname@:5432/postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://@eureka-server-service.hostname@:8761/eureka
    fetch-registry: true
    register-with-eureka: true
